version: "2"

services:

  app:
    build:
      context: app
      args:
        - MATTERMOST_HUBOT_USERNAME=matterbot
    volumes:
      - /opt/docker/matterbot/volumes/app/home/hubot/matterbot/scripts:/home/hubot/matterbot/scripts
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MATTERMOST_ENDPOINT=/hubot/incoming
      - MATTERMOST_SELFSIGNED_CERT=true
      - MATTERMOST_INCOME_URL=http://xxx.xxx.xxx/hooks/xxxxxxxxxxxxxxxxxxxxx
      - MATTERMOST_TOKEN=xxxxxxxxxxxxxxxxxxxx
    ports:
      - "8080:8080"
