- hosts: all

  vars:
    service: matterbot.service

  tasks:
    - name: set matterbot systemd service
      template: src="{{ service }}.j2" dest="/etc/systemd/system/{{ service }}"
      notify: matterbot restart

    - name: enable matterbot systemd service
      service: name="{{ service }}" enabled=yes state=started daemon_reload=yes

  handlers:
    - name: matterbot restart
      service: name=matterbot state=restarted
